[2025-07-05T06:12:02.512+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T06:12:02.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-04-28T00:00:00+00:00 map_index=1 [queued]>
[2025-07-05T06:12:02.747+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-04-28T00:00:00+00:00 map_index=1 [queued]>
[2025-07-05T06:12:02.759+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T06:12:03.379+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): add_one> on 2022-04-28 00:00:00+00:00
[2025-07-05T06:12:03.398+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2090) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-05T06:12:03.405+0000] {standard_task_runner.py:63} INFO - Started process 2246 to run task
[2025-07-05T06:12:03.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_dynamic_task_mapping', 'add_one', 'scheduled__2022-04-28T00:00:00+00:00', '--job-id', '320', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_dynamic_task_mapping.py', '--cfg-path', '/tmp/tmpqe0t9yen', '--map-index', '1']
[2025-07-05T06:12:03.438+0000] {standard_task_runner.py:91} INFO - Job 320: Subtask add_one
[2025-07-05T06:12:03.597+0000] {task_command.py:426} INFO - Running <TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-04-28T00:00:00+00:00 map_index=1 [running]> on host b39724c39614
[2025-07-05T06:12:03.891+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
