[2025-07-07T06:44:20.428+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T06:44:20.448+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lakehouse_pipeline.create_trino_table manual__2025-07-07T06:44:17.965999+00:00 [queued]>
[2025-07-07T06:44:20.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lakehouse_pipeline.create_trino_table manual__2025-07-07T06:44:17.965999+00:00 [queued]>
[2025-07-07T06:44:20.454+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-07T06:44:20.461+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_trino_table> on 2025-07-07 06:44:17.965999+00:00
[2025-07-07T06:44:20.467+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lakehouse_pipeline', 'create_trino_table', 'manual__2025-07-07T06:44:17.965999+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpemm9gyws']
[2025-07-07T06:44:20.469+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask create_trino_table
[2025-07-07T06:44:20.470+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-07T06:44:20.470+0000] {standard_task_runner.py:63} INFO - Started process 272 to run task
[2025-07-07T06:44:20.495+0000] {task_command.py:426} INFO - Running <TaskInstance: lakehouse_pipeline.create_trino_table manual__2025-07-07T06:44:17.965999+00:00 [running]> on host 5ff4c7b39ece
[2025-07-07T06:44:20.542+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lakehouse_pipeline' AIRFLOW_CTX_TASK_ID='create_trino_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:44:17.965999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:44:17.965999+00:00'
[2025-07-07T06:44:20.542+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T06:44:20.550+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T06:44:20.551+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        trino --server trino:8080 --catalog gold --schema default --execute "\n        CREATE TABLE IF NOT EXISTS order_summary (\n            customer_id VARCHAR,\n            total_amount DOUBLE\n        )\n        WITH (location = \'s3a://gold/warehouse/default/order_summary\')"\n        ']
[2025-07-07T06:44:20.559+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T06:44:21.032+0000] {subprocess.py:93} INFO - Jul 07, 2025 6:44:21 AM org.jline.utils.Log logr
[2025-07-07T06:44:21.033+0000] {subprocess.py:93} INFO - WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[2025-07-07T06:44:21.267+0000] {subprocess.py:93} INFO - Query 20250707_064421_00001_884xn failed: Schema default not found
[2025-07-07T06:44:21.267+0000] {subprocess.py:93} INFO - 
[2025-07-07T06:44:21.289+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-07T06:44:21.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T06:44:21.296+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-07T06:44:21.299+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=lakehouse_pipeline, task_id=create_trino_table, run_id=manual__2025-07-07T06:44:17.965999+00:00, execution_date=20250707T064417, start_date=20250707T064420, end_date=20250707T064421
[2025-07-07T06:44:21.305+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task create_trino_table (Bash command failed. The command returned a non-zero exit code 1.; 272)
[2025-07-07T06:44:21.325+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T06:44:21.348+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T06:44:21.350+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
