[2025-07-05T06:11:11.238+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T06:11:11.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_a scheduled__2025-07-04T00:00:00+00:00 [queued]>
[2025-07-05T06:11:11.377+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_a scheduled__2025-07-04T00:00:00+00:00 [queued]>
[2025-07-05T06:11:11.377+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T06:11:11.405+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalPythonOperator): ext_py_a> on 2025-07-04 00:00:00+00:00
[2025-07-05T06:11:11.418+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-05T06:11:11.419+0000] {standard_task_runner.py:63} INFO - Started process 1331 to run task
[2025-07-05T06:11:11.424+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_a', 'scheduled__2025-07-04T00:00:00+00:00', '--job-id', '179', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmpwl3_laa9']
[2025-07-05T06:11:11.426+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask ext_py_a
[2025-07-05T06:11:11.567+0000] {task_command.py:426} INFO - Running <TaskInstance: example_branch_operator.ext_py_a scheduled__2025-07-04T00:00:00+00:00 [running]> on host b39724c39614
[2025-07-05T06:11:11.832+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_a' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-04T00:00:00+00:00'
[2025-07-05T06:11:11.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T06:11:14.030+0000] {baseoperator.py:399} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-05T06:11:14.403+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callyute2w7o/script.py /tmp/venv-callyute2w7o/script.in /tmp/venv-callyute2w7o/script.out /tmp/venv-callyute2w7o/string_args.txt /tmp/venv-callyute2w7o/termination.log
[2025-07-05T06:11:14.415+0000] {process_utils.py:187} INFO - Output:
[2025-07-05T06:11:25.346+0000] {process_utils.py:191} INFO - Hello World from external Python
[2025-07-05T06:11:26.157+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-05T06:11:26.157+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T06:11:26.172+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_a, run_id=scheduled__2025-07-04T00:00:00+00:00, execution_date=20250704T000000, start_date=20250705T061111, end_date=20250705T061126
[2025-07-05T06:11:26.236+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-05T06:11:26.281+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-05T06:11:26.285+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
